---
title: "in-class-11/2"
format: html
embed-resources: true
editor: visual
---

## Ideas for final

hockey teams who has most points

which player has the most points

```{r}
library(moderndive)
library(tidyverse)
theme_set(theme_light())
```

```{r}
swift <- tribble(
  ~catches, ~yards, ~taylor,
       8.5,    108, "Present",
       7.0,   46.5, "Absent"
)

ggplot(swift,
       aes(x = taylor,
           fill = taylor,
           y = yards)) +
  geom_col() +
  labs(x = "Taylor Swift is...",
       y = "Receiving Yards",
       title = "Does Taylor Swift improve Travis Kelce's performances?") +
  theme(legend.position = "none")

```

```{r}
swift2 <- tribble(
  ~gw, ~yds, ~present,
  2, 26,   "Absent",
  3, 69,   "Present",
  4, 60,   "Present",
  5, 67,   "Absent",
  6, 124,  "Present",
  7, 179,  "Present",
  8, 58,   "Absent"
)
```

```{r}
ggplot(swift2,
       aes(x = yds,
           y = "",
           group = present,
           color = present)) +
  geom_jitter(width = .02,
              height = .02) +
  labs(color = "Swift is...",
       y = "",
       x = "Kelce receiving yards")
```

```{r}
mod1 <- lm(yds ~ present,
           data = swift2)

mod1_coefs <- get_regression_table(mod1)
mod1_coefs
```

```{r}
mod1_coefs |>
  filter(term == "present: Present") |> 
  ggplot(aes(x = estimate,
             xmax = upper_ci,
             xmin = lower_ci,
             y = "")) +
  geom_pointrange() +
  geom_vline(xintercept = 0,
             linetype = "dotted",
             color = "red") +
  scale_x_continuous(breaks = seq(-50, 200, 50),
                     limits = c(-50, 200)) +
  labs(y = "",
       x = "The Swift Effect",
       title = "Effect of Swift's Presence on Kelce's Receiving Yards",
       subtitle = "95% Confidence interval",
       caption = "Data from first 8 game weeks of 2023 NFL Season")
```

```{r}
head(bowl, n = 10)
```

```{r}
shovel1 <- bowl |> 
  rep_sample_n(size = 50)

shovel1
```

Ava: thinking about doing something with spotify like which artist has the most monthly listeners or which state has the most minutes listened to.

Sophie: university type/ranking has a different into job salary
